name: '🛠 Request NEW behavioural tracking for a Haven web app'
description: Want to know how Haven's guests and owners are using new features in web apps? Complete all of 'Section A', we'll then prioritise and refine your request.
assignees:
  - DawnTomlinAnalytics
projects: "HavenEngineering/128"

body:

  - type: markdown
    attributes:
      value: |

        Complete all parts in 'Section 🅰️' (look for the ➡️ icon). We'll complete 'Section B' when wew prioritise and refine your request in the "Assign & Refine" stage.

        ## 🅰️ Insight Requirement

  - type: textarea
    id: feature_summary
    attributes:
      label: "➡️ Feature summary"
      description: Provide summary description of the new feature.
      placeholder: e.g. We are adding a new Arrival Labels printing feature in the Experience Admin Tool.
    validations:
      required: true

  - type: input
    id: who
    attributes:
      label: "➡️ As a..."
      value: "Product Manager"
    validations:
      required: true

  - type: textarea
    id: requirement
    attributes:
      label: "➡️ I would like to..."
      description: "Provide details of the main requirement here."
      placeholder: "e.g. Understand how people are using our the new Arrival Labels printing feature in the Experience Admin Tool."
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "➡️ The objective..."
      description: "Provide details of the main objective."
      placeholder: "e.g. We can measure feature adoption, engagement and efficiency of use to get an understanding of where the Arrival Labels feature could be improved."
    validations:
      required: true

  - type: textarea
    id: questions
    attributes:
      label: "➡️ Key questions"
      description: "Give a summary list of the questions you need to be able to answer from the new tracking."
      placeholder: |
        e.g.
        - How many team members are generating Arrival Labels on a weekly basis?
        - How does this differ by park?
        - Are the team members generating labels en masse, or filtering and generating labels for smaller selections of arrivals?
        - On average, how long does it take a user to generate labels from when they view the printing feature?
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: "➡️ Links"
      description: "Provide links to the engineering ticket on the relevant squad's board and, where available, a link to final designs."
      value: |
        - Engineering ticket:
        - Final designs:
    validations:
      required: false

  - type: dropdown
    id: expected_quarter
    attributes:
      label: ➡️ Expected Quarter
      description: When is this expected to go live?
      options:
        - Q4 2025 (OCT, NOV, DEC)
        - Q1 2026 (JAN, FEB, MAR)
        - Q2 2026 (APR, MAY, JUN)
        - Q3 2026 (JUL, AUG, SEP)
      default: 1
    validations:
      required: true

  - type: input
    id: dependencies_blockers
    attributes:
      label: ➡️ Dependencies or Blockers
      description: "Please indicate which quater this will be needed for and highlight any blokers."
      placeholder: e.g. Need in Q2, will require release of UI update planned for 2026-07-01
    validations:
      required: false

  - type: dropdown
    id: Priority
    attributes:
      label: ➡️ Priority
      description: To help manage priorities for analytics tracking requests, please select one option below. This ensures transparency across teams and helps us handle competing demands effectively.Select one
      options:
        - P1-blocker (Must be delivered before launch)
        - P2-high (Important should be delivered in current sprint/release)
        - P3-medium (Needed for analysis/monitoring)
        - P4-low (Nice-to-have or exploratory)
      default: 2
    validations:
      required: true

  - type: markdown
    attributes:
      value: |

        > [!NOTE]
        > **Thank you for completing the briefing required to create the ticket. Please stop here — the Analytics team will take it from here.**

        ---

        ## 🅱️ dataLayer Specification

        > [!TIP]
        > ### Example Payload Structure
        >
        > ```javascript
        > window.dataLayer = window.dataLayer || [];
        > dataLayer.push({
        >   'event': 'some event',
        >   'stringVar': 'a string',
        >   'intVar': 1,
        >   'arrayVar': [{
        >     'arrayStringVar': 'a string',
        >     'arrayIntVar': 1
        >   },
        >   {
        >     'arrayStringVar': 'another string',
        >     'arrayIntVar': 5
        >   }],
        >   _clear: true // Remove if there is no array variable in the push
        > });
        > ```

  - type: textarea
    id: event_updates
    attributes:
      label: 🅱️ dataLayer Details
      description: Insert details of all required events, examples are provided for you to work from.
      value: |
        > [!Important]
        > **Event Guidelines**
        > Rules For Variable Value Formats
        > - Always use **lower case**, unless the value is an ID/code
        > - Avoid special characters (e.g. "&") in values
        > - Unless specified, values should not mirror UI labels directly

        ### 1) Loading arrival lists.
        - **Amplitude Event Name**: `'example name'`
        - **Trigger(s)**: When a user has x, then trigger the following event.
        ```javascript
        //Example payload here
        ```
    validations:
      required: false

  - type: textarea
    id: event_property_updates
    attributes:
      label: 🅱️ Event Property Details
      description: Insert details of the required variables, examples are provided for you to work from
      value:  |
        | Key | Description | Value Format | Example Values |
        | --- | --- | --- | --- |
        | **parkCode** | The park's code. | String, upper case.<br>Use `'ZZ'` for Hemel. | `'CG'` |
        | **arrivalDate** | The holiday arrival date. | String, 'yyyy-mm-dd'. | `'2025-05-09'` |
        | **labelCategory** | The type of label being generated. | String, lower case. | `'cleanliness label'`<br>`'door label'` |
        | **pagination** | The current page in view within the list. | String, lower case. | `'1 of 7'` |
        | **paginationFlag** | Specifies whether the current page's labels are being generated, or all pages of labels | String, lower case. | `'current page'`<br>`'all pages'` |
        | **numResults** | The total number of results across all paginations for the list in its current filtered state. | Integer | `142` |
    validations:
      required: false

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ Checklist
      description: To be completd by the Analytics team.
      value:  |
        - [ ] dataLayer spec written
        - [ ] dataLayer events built in dev site
        - [ ] dataLayer QA completed in dev
          - [ ] dataLayer events trigger correctly on specified interactions
          - [ ] dataLayer payload matches the spec
          - [ ] All values are accurately populated and in the correct formats
        - [ ] GTM config completed
          - [ ] Events correctly sending to Amplitude
          - [ ] Events correctly sending to marketing stack
          - [ ] Blocking triggers checked to ensure consent compliance
        - [ ] Tool config completed
          - [ ] Events correctly added to Amplitude data schema (including categories and metadata)
          - [ ] Events correctly added to marketing tools, appearing in charts
        - [ ] Publish
        - [ ] Post-live QA completed
           - [ ] All events appearing as expected in Amplitude charts
           - [ ] All events appearing as expected in marketing stack
        - [ ] Amplitude event streaming (if required)
          - [ ] Events correctly streaming to Bloomreach
          - [ ] Events correctly streaming to SmartSeer
        - [ ] Update documentation
          - [ ] Amplitude SDR
          - [ ] Marketing tags tracker
        - [ ] Communicate/ demo
          - [ ] To analysts
          - [ ] To relevant product squad(s)
          - [ ] To other relevant end users (e.g. media trading, etc)
    validations:
      required: false
