name: '🐞 Report a BUG with our behavioural tracking or data'
description: Something looking odd in our behavioural data? Data pushes misbehaving in our web/ native apps? Let us know! Complete all parts in 'Section A' and we'll take care of the rest.
assignees:
  - DawnTomlinAnalytics
type: "Bug"
projects: "HavenEngineering/128"

body:
  - type: markdown
    attributes:
      value: |
        Complete all of section A and move to "Heads Up" and we'll complete the rest.

  - type: input
    id: issue_summary
    attributes:
      label: 🅰️ Issue Summary
      description: Brief description of the issue
      placeholder: e.g. Missing event on product page view
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: ➡️ Current Behaviour with Example of Bug/Data Issue
      description: Describe what's happening now. Include specific events, properties, or tracking IDs affected. Also provide a URL, reproduction steps, console output, or screenshots.
      placeholder: Event "product_viewed" is not firing on PDP for variant pages. Example, Navigate to PDP, check dev tools > network tab.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ➡️ Expected Behaviour
      description: What should be happening instead?
      placeholder: Event "product_viewed" should trigger on PDP load
    validations:
      required: true

  - type: input
    id: impact
    attributes:
      label: ➡️ Impact of Issue
      description: How is this issue affecting reporting or decision-making? Who is impacted?
      placeholder: Funnel reporting for PDP drop-off is skewed; trade team impacted
    validations:
      required: false

  - type: markdown
    attributes:
      value: |

        > [!NOTE]
        > **Thank you for completing the details required to create the bug ticket. Please stop here — the Analytics team will take it from here.**

        ---
  - type: textarea
    id: fix_details
    attributes:
      label: 🅱️ Fix Details
      description: Analytics team to investigate and outline required fix below.
      placeholder:
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: ✅ Acceptance Criteria
      options:
        - label: Issue investigated – details outlined
        - label: Bug example confirmed
        - label: Root cause identified
        - label: Fix planned (Amplitude config / dataLayer update / etc.)
        - label: Tool config updated
        - label: Post-live QA completed
